// Ингредиенты- список
export const BURGER_INGREDIENTS_QUERY = "BURGER_INGREDIENTS_QUERY";//Запрашиваем
export const BURGER_INGREDIENTS_SUCCESS = "BURGER_INGREDIENTS_SUCCESS";
export const BURGER_INGREDIENTS_ERROR = "BURGER_INGREDIENTS_ERROR";
//конструктор
export const BURGER_CONSTRUCTOR_ADD_INGREDIENT = "BURGER_CONSTRUCTOR_ADD_INGREDIENT";
export const BURGER_CONSTRUCTOR_CHANGE_BUN = "BURGER_CONSTRUCTOR_CHANGE_BUN";
export const BURGER_CONSTRUCTOR_DELETE = "BURGER_CONSTRUCTOR_DELETE";
export const BURGER_CONSTRUCTOR_SORT = "BURGER_CONSTRUCTOR_SORT";
export const BURGER_CONSTRUCTOR_MOVE = "BURGER_CONSTRUCTOR_MOVE";
export const BURGER_CONSTRUCTOR_CLEAR = "BURGER_CONSTRUCTOR_CLEAR";


//Номер заказа
export const ORDERDETAILS_QUERY = "ORDERDETAILS_QUERY";
export const ORDERDETAILS_SUCCESS = "ORDERDETAILS_SUCCESS";
export const ORDERDETAILS_ERROR = "ORDERDETAILS_ERROR";
export const ORDERDETAILS_DELETE = "ORDERDETAILS_DELETE";



//Ингредиент
export const INGREDIENTDETAILS_QUERY = "INGREDIENTDETAILS_QUERY";
export const INGREDIENTDETAILS_CLOSE = "INGREDIENTDETAILS_CLOSE";
export const  INGREDIENTDETAILS_ERROR = 'ORDERDETAILS_ERROR';

