export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_SUCCESS";

export const USER_GET_DATA_SUCCESS ="USER_UPDATE_DATA_SUCCESS";
export const USER_UPDATE_DATA_SUCCESS ="USER_UPDATE_DATA_SUCCESS";
export const USER_UPDATE_DATA_ERROR ="USER_UPDATE_DATA_ERROR";

export const PASSWORD_REFRESH_SUCCESS = "PASSWORD_REFRESH_SUCCESS";
export const PASSWORD_REFRESH_ERROR ="PASSWORD_REFRESH_ERROR";

export const PASSWORD_NEW_SUCCESS = "PASSWORD_NEW_SUCCESS";
export const PASSWORD_NEW_ERROR = "PASSWORD_NEW_ERROR";

export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";
export const TOKEN_REFRESH_ERROR = "TOKEN_REFRESH_ERROR";

export const USER_EXIT_SUCCESS ="USER_EXIT_SUCCESS";
export const USER_EXIT_ERROR ="USER_EXIT_ERROR";

export const AUTH_CHECKED  ="AUTH_CHECKED";